version: '3.7'
services:
  db:
    image: postgres:14.0
    hostname: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  cache:
    image: redis
    hostname: cache
    ports:
      - "6379:6379"
    networks:
      - app-network
  app:
    build: .
    command: bash -c "poetry run wt-db upgrade head && poetry run wt-api"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env
networks:
  app-network: