"""Remove unique constrait on username

Revision ID: af4d214f3013
Revises: a3c4050fb8c0
Create Date: 2023-07-09 21:42:15.684023
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af4d214f3013'
down_revision = 'a3c4050fb8c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###
